# Site settings
title: Nathan Bartley's Research/Personal Site
email: ntbartley(at)gmail.com
description: >
  PhD graduate at University of Southern California, researching Recommender Systems
  applied to Online Social Networks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bartleyn.github.io/" # the base hostname & protocol for your site
twitter_username: reichaos
github_username:  bartleyn

# Build settings
markdown: kramdown


defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
